# Generated by Django 5.1.5 on 2025-01-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="accessories",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="clothing",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
